### ISSUE TITLE
kcgi 0.10.0 broke kcaldav

### ISSUE THREAD

**Issue by jturner** [kristapsdz/kcaldav#4]
With the recent release of kcgi 0.10.0 kcaldav no longer compiles. I believe mainly because of the changes from this commit: https://github.com/kristapsdz/kcgi/commit/42d2bdaf16f129e12e4e1bce5d495bd54fd4d17d

**Comment by kristapsdz** [comment]
This is finally getting fixed!  (I got tired of not having my calendar.)  It works now with what's been checked in, although the port may need to be tweaked.  It now has a `configure` script and saner Makefile.  (No more gmake!)

I'm going to add some pledge goodness in the morning and continue testing it on my other devices.
