### ISSUE TITLE
Carddav support?

### ISSUE THREAD

**Issue by bapt** [kristapsdz/kcaldav#6]
Any plan to add support for CardDav? or to make a kcarddav?

**Comment by mc3** [comment]
As Apples OSS calendarserver [](https://www.calendarserver.org/) (dcs) is being deprecated due to lack of porting from Python2 to Python3, it would be nice to have a minimalistic CardDAV server, based on kcaldav. 
Could pull dcs users to kcaldav.

**Comment by kristapsdz** [comment]
Patches, folks, patches!  I'm happy to spend time going through patches and answering questions.  I don't use carddav myself, so it's not gonna happen unless funded or developed by somebody else.
