### ISSUE TITLE
kcaldav does not handle Content-Type: application/xml

### ISSUE THREAD

**Issue by mk-f** [kristapsdz/kcaldav#8]
kcaldav only accepts ``text/xml`` as Content-Type in ``propfind`` / ``proppatch`` and therefore excludes clients which use ``application/xml``.

It seems like the use of ``text/xml`` in WebDAV-context is actually [deprecated](https://tools.ietf.org/html/rfc4918#section-8.2):

>   When XML is used for a request or response body, the Content-Type
>    type SHOULD be application/xml.  Implementations MUST accept both
>    text/xml and application/xml in request and response bodies.  Use of
>    text/xml is deprecated.

Probably it would be useful to adding ``application/xml`` as valid type to [kcgi](https://github.com/kristapsdz/kcgi) instead of adding it only to kcaldav.

**Comment by kristapsdz** [comment]
I've just pushed this into kcgi and will follow that with an update to kcaldav.  Thanks!

**Comment by kristapsdz** [comment]
Ok, this last commit should do it---but again, as noted in issues/7, I haven't tested it yet.  Will do so shortly.
